version: "3"

volumes:
  qm-data:

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - qm-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=quizmaster

  redis:
    image: redis
    ports:
      - 6379:6379

  quizmaster:
    build:
      context: ./
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - PORT=8080
